---
- name: build an artifact
  hosts: builder
  become: true

  tasks:
    - name: Update repositories cache
      apt:
        update_cache: true

    - name: Ensure default-jre package is present
      apt:
        name: default-jre
        state: present

    - name: Ensure maven package is present
      apt:
        name: maven
        state: present

    - name: Ensure git package is present
      apt:
        name: git
        state: present

    - name: Clone a github repository boxfuse
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /root/boxfuse
        clone: true
        update: true
      register: git_status

    - name: Clean maven profect if git repo changed
      shell:
        chdir: /root/boxfuse
        cmd: mvn clean
      when: git_status.changed

    - name: Check the artifact exists
      stat:
        path: /root/boxfuse/target/hello-1.0.war
      register: artifact_file

    - name: Build an artifact if it doesn't exist
      shell:
        chdir: /root/boxfuse
        cmd: mvn package
      when: not artifact_file.stat.exists
      register: build_status

    - name: Fetch file to the local machine
      fetch:
        src: /root/boxfuse/target/hello-1.0.war
        dest: /root/hello-1.0.war
        flat: true
      when: build_status.changed and build_status is succeeded
      register: fetch_status

    - name: Backup new artifact locally
      copy:
        src: /root/hello-1.0.war
        dest: "/root/hello-1.0_{{ ansible_date_time.iso8601_basic_short }}.war"
      delegate_to: localhost
      when: fetch_status.changed and fetch_status is succeeded


- name: install tomcat
  hosts: web
  become: true

  tasks:
    - name: Update repositories cache
      apt:
        update_cache: true

    - name: Ensure tomcat package is present
      apt:
        name: tomcat9
        state: present

    - name: Ensure tomcat is running
      service:
        name: tomcat9.service
        state: started

    - name: Check new artifact exists
      stat:
        path: /root/hello-1.0.war
      delegate_to: localhost
      register: artifact_file

    - name: Install new artifact
      copy:
        src: /root/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/root.war
      when: artifact_file.stat.exists
      register: install_status

    - name: Delete new artifact locally
      file:
        path: /root/hello-1.0.war
        state: absent
      delegate_to: localhost
      when: install_status is succeeded
